---
all:
  vars:
    admin_user: 'sean'
    admin_pass: 'asdfb'
    ansible_user: 'ansible'
    kubernetes_user: 'kubernetes'
    network_cidr: '192.168.66.0/24'
    local_dns:
      - 192.168.66.11
      - 1.1.1.1                       # Cloudflare
      - 1.0.0.1                       # Cloudflare
    ntp_servers:
      - '0.pool.ntp.org'
      - '1.pool.ntp.org'
      - '2.pool.ntp.org'
      - '3.pool.ntp.org'
  hosts:
    nephilim:
      ansible_host: 192.168.0.100
      ansible_python_interpreter: '/usr/bin/python3'
    kube-00:
      ansible_host: 192.168.0.10
      ansible_python_interpreter: '/usr/bin/python3'
    kube-01:
      ansible_host: 192.168.0.11
      ansible_python_interpreter: '/usr/bin/python3'
    kube-02:
      ansible_host: 192.168.0.12
      ansible_python_interpreter: '/usr/bin/python3'
  children:
    workstations:
      hosts:
        nephilim:
    servers:
      hosts:
        kube-00:
        kube-01:
        kube-02:
    kubernetes:
      hosts:
        kube-00:
          kube_master: true
        kube-01:
          kube_master: false
        kube-02:
          kube_master: false
    linux:
      hosts:
        nephilim:
        kube-00:
        kube-01:
        kube-02:
    file_shares:
      hosts:
        nephilim:
          nfs_role: 'server'
          nfs_root: '/media/Storage/nfs_shares'
          nfs_shares: '/media/Storage/Data'
        kube-00:
          nfs_role: 'client'
        kube-01:
          nfs_role: 'client'
        kube-02:
          nfs_role: 'client'
