---
all:
  vars:
    admin_user: 'sean'
    admin_pass: 'asdfb'
    ansible_user: 'ansible'
    kubernetes_user: 'kubernetes'
    network_cidr: '192.168.1.0/24'
    gateway_ip: '192.168.1.1'
    local_dns: '1.1.1.1, 1.0.0.1'
    ntp_servers:
      - '0.pool.ntp.org'
      - '1.pool.ntp.org'
      - '2.pool.ntp.org'
      - '3.pool.ntp.org'
  hosts:
    #nephilim:
    #  ansible_host: 192.168.0.100
    #  ansible_python_interpreter: '/usr/bin/python3'
    PL-KUBE-00:
      ansible_host: 192.168.1.190
      ansible_python_interpreter: '/usr/bin/python3'
      device_cpu: 'arm64'
    # kube-01:
    #   ansible_host: 192.168.1.191
    #   ansible_python_interpreter: '/usr/bin/python3'
    # kube-02:
    #   ansible_host: 192.168.1.192
    #   ansible_python_interpreter: '/usr/bin/python3'
  children:
    workstations:
      hosts:
        #nephilim:
    servers:
      hosts:
        PL-KUBE-00:
        #kube-01:
        #kube-02:
    kubernetes:
      hosts:
        PL-KUBE-00:
          kube_master: true
        #kube-01:
          #kube_master: false
        #kube-02:
          #kube_master: false
    linux:
      hosts:
        #nephilim:
        PL-KUBE-00:
        #kube-01:
        #kube-02:
    #file_shares:
    #  hosts:
    #    nephilim:
    #      nfs_role: 'server'
    #      nfs_root: '/media/Storage/nfs_shares'
    #      nfs_shares: '/media/Storage/Data'
    #    kube-00:
    #      nfs_role: 'client'
    #    kube-01:
    #      nfs_role: 'client'
    #    kube-02:
    #      nfs_role: 'client'
