---
# tasks file for sft.docker
- name: Ensure dependencies are installed
  become: true
  ansible.builtin.apt:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: latest
    update_cache: true
    cache_valid_time: 3600
    install_recommends: true

- name: Add Docker apt key
  become: true
  ansible.builtin.apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    keyring: "{{ keyring }}"
    state: present

- name: Add Docker apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ device_cpu }} signed-by={{ keyring }}] {{ docker_url }} {{ ansible_distribution_release }} stable"
    filename: '/etc/apt/sources.list.d/docker'
    state: present

- name: Install Docker
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    install_recommends: true
    update_cache: true

- name: Enable and start docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Configure cgroups to use systemd
  become: true
  ansible.builtin.copy:
    src: 'daemon.json'
    dest: '/etc/docker/daemon.json'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: Store contents of cmdline file
  ansible.builtin.slurp:
    src: '/boot/firmware/cmdline.txt'
  register: cmdline

- name: Store the contents of cmdline in a variable to manipulate
  ansible.builtin.set_fact:
    cmdline_string: "{{ cmdline['content'] | b64decode | trim }}"

- name: Generate the string that should be added to the cmdline file
  ansible.builtin.set_fact:
    cmdline_string: "{{ cmdline_string }} {{ item }}"
  when: not cmdline['content'] | b64decode | regex_search(item | string)
  with_items: "{{ limit_settings }}"

- name: Enable limit support for the pi
  become: true
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    regexp: "{{ cmdline['content'] | b64decode }}"
    line: "{{ cmdline_string }}"
  register: needs_reboot

- name: Reboot device
  become: true
  ansible.builtin.reboot:
  when: needs_reboot is changed
