---
# tasks file for sft.python3
- name: Install Python3 and pip3
  become: true
  pacman:
    name: 
      - python3
      - python-pip
    state: latest
  when: ansible_pkg_mgr == 'pacman'

- name: Install Python3
  become: true
  apt:
    name: 
      - python3
      - python3-pip
    state: latest
  when: ansible_pkg_mgr == 'apt'
