---
# tasks file for sft.helm
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - 'apt-transport-https'
  when: ansible_pkg_mgr == 'apt'

- name: Add apt key for helm
  become: true
  ansible.builtin.apt_key:
    url: 'https://baltocdn.com/helm/signing.asc'
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: Add helm repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm-stable-debian
  when: ansible_pkg_mgr == 'apt'

- name: Install helm
  become: true
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true
    install_recommends: true
  when: ansible_pkg_mgr == 'apt'

