---
- hosts: all
  gather_facts: false
  tasks:
    - name: Test connection
      ansible.builtin.ping:

- hosts: all
  gather_facts: true
  roles:
    - ../roles/cfg.manage_users
    - ../roles/sft.python3
    - ../roles/cfg.security_configuration
