---
- hosts: kubernetes
  gather_facts: true
  roles:
    - ../roles/sft.docker
    - ../roles/sft.kubernetes
    - {role: '../roles/sft.helm', when: kube_master == true} 
    - {role: '../roles/kub.nginx_ingress', when: kube_master == true}
